name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          port: ${{secrets.SSH_PORT}} 
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          known_hosts: github.com
        
     
          script: |
            if [ -d "/var/app/${{ secrets.APP_NAME }}" ]; then git pull && cd /var/app/${{ secrets.APP_NAME }} && pm2 restart ${{ secrets.APP_NAME }}; else cd /var/app/ && git clone git@github.com:jspawar80/ci-cd-to-digitalocean-with-github-actions.git/${{ secrets.APP_NAME }}.git && cd /var/app/${{ secrets.APP_NAME }} && npm i && pm2 start index.js --name "${{ secrets.APP_NAME }}" &&  echo "Error: Directory /var/app/${{ secrets.APP_NAME }} dir already exists."; fi
